spring.application.name=foodapp-backend

spring.datasource.url=${DB_HOST}
spring.datasource.username=${DB_NAME}
spring.datasource.password=${DB_PASS}

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_schema=${DEF_SCHEMA}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXP}

# Multipart File Upload Settings
spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=15MB

file.upload-dir=uploaded_images/

#file.upload-dir=/opt/render/project/src/uploaded_images/

server.port=8085
server.address=0.0.0.0

# Updated base URL for Render deployment
app.base-url=http://192.168.0.42:8085

