spring.application.name=foodapp-backend

spring.datasource.url=jdbc:postgresql://ep-rough-haze-a18iashw-pooler.ap-southeast-1.aws.neon.tech:5432/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_vWzZQdJ82Ppt

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_schema=foodapp
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JWT
jwt.secret=6A576E5A7234753778214125442A472D4B6150645367566B5970337336763979
jwt.expiration=172800000

# Multipart File Upload Settings
spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=15MB

file.upload-dir=uploaded_images/

#file.upload-dir=/opt/render/project/src/uploaded_images/

server.port=8085
server.address=0.0.0.0

# Updated base URL for Render deployment
app.base-url=http://192.168.0.42:8085

